### ISSUE TITLE
Panics when encountering an unknown rule

### ISSUE THREAD

**Issue by mattgen88** [vanng822/css#1]
I have a rule that includes a browser specific prefix, that rule causes a panic.
@-webkit-keyframes
, 
It'd be better if this instead marked a rule as unknown in a data structure or skipped processing it instead of panicking, I would think.

Panic occurs here:
https://github.com/vanng822/css/blob/453b58786e0ab69b6775dc8b2b92fa61a3bb4516/parser.go#L128

**Comment by vanng822** [comment]
Thanks for reporting @mattgen88 
Yeah we could definitely skip the rule and probably log something

**Comment by vanng822** [comment]
Would you like to take on the issue @mattgen88 ?

**Comment by mattgen88** [comment]
For me to contribute means some red tape for approval to do so. Since I'm not even sure this project meets my needs, I am not at this time willing to try and contribute at this time, sorry.

**Comment by vanng822** [comment]
this should be fixed, this specific rule and skip unsupported rules instead of panic
