### ISSUE TITLE
unnecessary fmt.Printf pollutes the output in production

### ISSUE THREAD

**Issue by micaelAlastor** [vanng822/css#4]
https://github.com/vanng822/css/blob/3640fb0faa9b9ebd2c0b0fe8657537b8f8d4ae5a/parser.go#L131

probably should be just   
`log.Printf("Skip unsupported atrule: %s", token.Value)` 
since every log message is output on a separate line anyway

**Comment by vanng822** [comment]
fixed in v1.0.1
